### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by bpavesi** [sonertari/SSLproxy#16] opened 2019-12-02 19:16 UTC
on **Linux test-vmpc 5.0.0-36-generic #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux**

i get segmentation fault
 
with ./sslproxy  -k ca.key -c ca.crt https 0.0.0.0 8443 up:8445

**Comment by sonertari** [comment] 2019-12-02 20:59
Since I don't have any problems on Linux Mint 19 with kernels 5.0/5.3 and default libraries, I don't think you would get a segmentation fault on Ubuntu 18.04 either if you do the same. I don't know what sslproxy configuration you are using other than that command line. I hope you are using a listening program, but it cannot cause segmentation fault even if you aren't.

So, we need more information to figure out what's going on. Can you turn on DEBUG_* macros in GNUmakefile, compile, run with the -D4 option to sslproxy, and check if you can see anything in those verbose debug logs? You can capture and share them with me if you like.

**Comment by alfreema** [comment] 2020-02-13 17:10
We are trying to get it working on OpenWRT, and having some luck but also getting segmentation fault when trying to use https.   It works great with http.

A gdb stack trace thinks it's bombing in main_check_opts:

> (gdb) run
> Starting program: /usr/bin/sslproxy -t /etc/sslproxy https 192.168.8.1 8080 up:8000
> warning: Unable to find dynamic linker breakpoint function.
> GDB will be unable to debug shared library initializers
> and track explicitly loaded dynamic code.
> 
> Program received signal SIGSEGV, Segmentation fault.
> 0x00419cf4 in main_check_opts (opts=0x77ef4c40, argv0=argv0@entry=0x7fffeea2 "/usr/bin/sslproxy") at main.c:336
> 336     main.c: No such file or directory.
> (gdb) print opts
> $1 = (opts_t *) 0x77ef4c40
> (gdb)

Here is the version information for sslproxy:

> root@OpenWrt:~# sslproxy -V
> SSLproxy v0.7.0-dirty (built 2020-02-12)
> Copyright (c) 2017-2019, Soner Tari <sonertari@gmail.com>
> https://github.com/sonertari/SSLproxy
> Copyright (c) 2009-2019, Daniel Roethlisberger <daniel@roe.ch>
> https://www.roe.ch/SSLsplit
> Build info: V:GIT
> Features: -DHAVE_NETFILTER
> NAT engines: netfilter* tproxy
> netfilter: IP_TRANSPARENT IP6T_SO_ORIGINAL_DST
> Local process info support: no
> compiled against OpenSSL 1.0.2u  20 Dec 2019 (1000215f)
> rtlinked against OpenSSL 1.0.2o  27 Mar 2018 (100020ff)
> OpenSSL has support for TLS extensions
> TLS Server Name Indication (SNI) supported
> OpenSSL is thread-safe with THREADID
> OpenSSL has engine support
> Using SSL_MODE_RELEASE_BUFFERS
> SSL/TLS protocol availability: tls10 tls11 tls12
> SSL/TLS algorithm availability: !SHA0 RSA DSA ECDSA DH ECDH EC
> OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
> compiled against libevent 2.0.22-stable
> rtlinked against libevent 2.0.22-stable
> compiled against libnet 1.2-rc3
> rtlinked against libnet 1.2-rc3
> compiled against libpcap n/a
> rtlinked against libpcap 1.8.1
> compiled against sqlite 3.31.1
> rtlinked against sqlite 3.23.1
> 1 CPU cores detected

And here are kernel details:

> root@OpenWrt:~# uname -a
> Linux OpenWrt 4.14.63 #0 Thu Aug 16 07:51:15 2018 mips GNU/Linux

**Comment by sonertari** [comment] 2020-02-13 20:31
You need to use -c and -k options with https, instead of -t (you can experiment with it later when you successfully run it). So you first need to generate the CA cert and key for sslproxy to forge certificates, and pass them to sslproxy using -c and -k. The segmentation fault you are getting is related to that. (The OP of this issue may be having other problems, I don't know.)

And if you can, try to compile and run sslproxy with libevent 2.1.11. Because 2.0.22 exits if the ssl connection does not terminate gracefully, but that's actually a minor error, which 2.1.11 handles better.

**Comment by alfreema** [comment] 2020-02-14 01:19
Ah, the -t was just a test.  We have been using -c and -k right along with the same seg fault in the same line.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sonertari** [comment] 2020-02-14 01:56
If you look at the line 336 in main.c, there are 3 possible paths it may be complaining about: CA cert, CA key, or target crt directory. If you do not have the -t option, but are using -c and -k options, then I think sslproxy cannot find the CA cert or key file. Perhaps the path is wrong (I am not sure what happens if the permissions are wrong).

If you want to get detailed debug logs (but the output you have provided is specific enough in this case), you can recompile sslproxy with DEBUG_PROXY macro, and then start it with the -D4 option. Please keep trying, because I guess it is something very simple.

Btw, if you want to see sslproxy running successfully, you can download the iso file of [UTMFW](https://github.com/sonertari/UTMFW) and try it for yourself.

**Comment by sonertari** [comment] 2020-02-14 06:44
Alright, I can confirm that there is a problem when you use those command line options. While I am working on a fix, please use a configuration file instead. So basically, create a config file like `sslproxy.conf` with the following contents, and pass it to sslproxy with the -f option:
```
CACert ca.crt
CAKey ca.key
ProxySpec https 192.168.8.1 8080 up:8000
```
This should run without any issues. In fact, please use a configuration file for all of the options you want to try, for now (using a configuration file is easier too).

**Comment by tuncayaskin** [comment] 2020-02-14 08:54
I have a same issue sslproxy version 0.7.0. I am using ubuntu server 18.04. When i installed and used sslproxy 0.6.0 and 0.5.9, there wasn't problem. However, when ı used version 0.7, program giving error "segmentation fault(core dumped)".

**Comment by sonertari** [comment] 2020-02-14 09:36
@bpavesi, @alfreema, @tuncayaskin My latest commit to the develop branch fixes this issue. Please try and report back.

**Comment by tuncayaskin** [comment] 2020-02-14 11:45
@sonertari It is working.

**Comment by tuncayaskin** [comment] 2020-02-14 11:46
@sonertari it is working. there is no issue about segmentation.

**Comment by alfreema** [comment] 2020-02-14 15:21
Can also confirm it's working well!

**Comment by sonertari** [comment] 2020-02-15 06:15
Thanks for reporting back.

**Comment by sxsexton** [comment] 2020-02-28 14:29
Will you be creating a new release with this fix?

**Comment by sonertari** [comment] 2020-02-28 15:35
This fix is not so urgent actually. Because you wouldn't recognize this issue if you use a configuration file instead of passing the options on the command line. So, the next release may not be so soon.

**Comment by sonertari** [comment] 2020-06-24 20:02
[v0.8.0](https://github.com/sonertari/SSLproxy/releases/tag/v0.8.0) includes this fix now. So I am closing this issue.

**Closed by sonertari** 2020-06-24 20:02 UTC
Labels: bug
